[package]
name = "luftraum"
version = "0.1.2"
edition = "2024"

[dependencies]
bevy = "0.16.0"
bevy_panorbit_camera = "0.26.0"
bevy_egui = "0.34.1"
tokio = { version = "1.44.2", features = ["full"] }
chrono = "0.4.41"