[package]
name = "luftraum"
version = "0.1.8"
edition = "2024"

[dev-dependencies]
divan = "0.1.21"

[[bench]]
name = "benchmarks"
harness = false

[dependencies]
# bevy = { version = "0.16.1", features = ["meshlet", "meshlet_processor"] }
bevy = "0.16.1"
bevy_panorbit_camera = "0.26.0"


bevy_egui = "0.35.1"
# Egui crate 0.34.1 panics on app exit
# Crash fix
#bevy_egui = { git = "https://github.com/vladbat00/bevy_egui.git", branch = "fix-panic-on-window-close" }

# Used for images within egui
egui_extras = { version = "*", features = ["all_loaders"] }
image = { version = "0.25.6", features = ["png"] }

tokio = { version = "1.45.1", features = ["full"] }
chrono = "0.4.41"

# Performance monitoring
dhat = "0.3.3"

[features]
dhat-heap = []

[profile.release]
debug = true